### ISSUE TITLE
ability to turn off and on without config change

### ISSUE THREAD

**Issue by adamfoneil** [adamfoneil/CodeProfiler#2]
I'd like to be able to turn profiling on and off without changing app settings (and therefore without restarting the app).

**Comment by adamfoneil** [comment]
No, I think what I really want is a retention period that keeps the log size under control

**Comment by tradev001** [comment]
Reporting to your company Plz Corp,

Will be done by today.

Wait for your luck... loosing your day job

You are AWESOME!
